//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCars.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ProjectCars.ServiceReference1.HelloWorldResponse HelloWorld(ProjectCars.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ProjectCars.ServiceReference1.HelloWorldResponse> HelloWorldAsync(ProjectCars.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name Fnametxt from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Debit", ReplyAction="*")]
        ProjectCars.ServiceReference1.DebitResponse Debit(ProjectCars.ServiceReference1.DebitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Debit", ReplyAction="*")]
        System.Threading.Tasks.Task<ProjectCars.ServiceReference1.DebitResponse> DebitAsync(ProjectCars.ServiceReference1.DebitRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ProjectCars.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ProjectCars.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProjectCars.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ProjectCars.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DebitRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Debit", Namespace="http://tempuri.org/", Order=0)]
        public ProjectCars.ServiceReference1.DebitRequestBody Body;
        
        public DebitRequest() {
        }
        
        public DebitRequest(ProjectCars.ServiceReference1.DebitRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DebitRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Fnametxt;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cvv;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cardnum;
        
        public DebitRequestBody() {
        }
        
        public DebitRequestBody(string Fnametxt, string cvv, string cardnum) {
            this.Fnametxt = Fnametxt;
            this.cvv = cvv;
            this.cardnum = cardnum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DebitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DebitResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProjectCars.ServiceReference1.DebitResponseBody Body;
        
        public DebitResponse() {
        }
        
        public DebitResponse(ProjectCars.ServiceReference1.DebitResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DebitResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DebitResult;
        
        public DebitResponseBody() {
        }
        
        public DebitResponseBody(string DebitResult) {
            this.DebitResult = DebitResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ProjectCars.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ProjectCars.ServiceReference1.WebService1Soap>, ProjectCars.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjectCars.ServiceReference1.HelloWorldResponse ProjectCars.ServiceReference1.WebService1Soap.HelloWorld(ProjectCars.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ProjectCars.ServiceReference1.HelloWorldRequest inValue = new ProjectCars.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ProjectCars.ServiceReference1.HelloWorldRequestBody();
            ProjectCars.ServiceReference1.HelloWorldResponse retVal = ((ProjectCars.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProjectCars.ServiceReference1.HelloWorldResponse> ProjectCars.ServiceReference1.WebService1Soap.HelloWorldAsync(ProjectCars.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProjectCars.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            ProjectCars.ServiceReference1.HelloWorldRequest inValue = new ProjectCars.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ProjectCars.ServiceReference1.HelloWorldRequestBody();
            return ((ProjectCars.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjectCars.ServiceReference1.DebitResponse ProjectCars.ServiceReference1.WebService1Soap.Debit(ProjectCars.ServiceReference1.DebitRequest request) {
            return base.Channel.Debit(request);
        }
        
        public string Debit(string Fnametxt, string cvv, string cardnum) {
            ProjectCars.ServiceReference1.DebitRequest inValue = new ProjectCars.ServiceReference1.DebitRequest();
            inValue.Body = new ProjectCars.ServiceReference1.DebitRequestBody();
            inValue.Body.Fnametxt = Fnametxt;
            inValue.Body.cvv = cvv;
            inValue.Body.cardnum = cardnum;
            ProjectCars.ServiceReference1.DebitResponse retVal = ((ProjectCars.ServiceReference1.WebService1Soap)(this)).Debit(inValue);
            return retVal.Body.DebitResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProjectCars.ServiceReference1.DebitResponse> ProjectCars.ServiceReference1.WebService1Soap.DebitAsync(ProjectCars.ServiceReference1.DebitRequest request) {
            return base.Channel.DebitAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProjectCars.ServiceReference1.DebitResponse> DebitAsync(string Fnametxt, string cvv, string cardnum) {
            ProjectCars.ServiceReference1.DebitRequest inValue = new ProjectCars.ServiceReference1.DebitRequest();
            inValue.Body = new ProjectCars.ServiceReference1.DebitRequestBody();
            inValue.Body.Fnametxt = Fnametxt;
            inValue.Body.cvv = cvv;
            inValue.Body.cardnum = cardnum;
            return ((ProjectCars.ServiceReference1.WebService1Soap)(this)).DebitAsync(inValue);
        }
    }
}
